import type { Request, Response } from 'express';
import { createHash, createHmac, timingSafeEqual } from 'node:crypto';
import { dbExec, dbQuery, ensureArchiveDatabase } from './neonDb.js';
import { SAUDI_REGIONS } from './data/saudiRegions.js';
import { calculateFarePrices, ensurePricingSchema } from './services/pricingEngine.js';
import { ensureInternationalSchema, listInternationalCities, listInternationalCountries, listInternationalRoutes } from './services/internationalCatalog.js';

type Row = Record<string, any>;
type AdminSession = { user:{id:number;name:string;email:string;role:string}; csrf:string; exp:number };
const COOKIE='sat_archive_admin';
const SECRET=process.env.SESSION_SECRET||'';
const text=(v:unknown,max=255)=>String(v??'').trim().slice(0,max);
const num=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const bool=(v:unknown)=>v===true||v===1||v==='1'||v==='true'||v==='on';
const json=(res:Response,body:unknown,status=200)=>res.status(status).setHeader('Cache-Control','no-store').json(body);
function cookies(h?:string){const out:Record<string,string>={};for(const p of String(h||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
function key(){return createHash('sha256').update(SECRET||'unconfigured').digest()}
function sign(v:string){return createHmac('sha256',key()).update(v).digest('base64url')}
function session(req:Request):AdminSession|null{const t=cookies(req.headers.cookie)[COOKIE];if(!t||SECRET.length<32)return null;const[p,s]=t.split('.');if(!p||!s)return null;const a=Buffer.from(s),b=Buffer.from(sign(p));if(a.length!==b.length||!timingSafeEqual(a,b))return null;try{const x=JSON.parse(Buffer.from(p,'base64url').toString('utf8')) as AdminSession;return x?.user?.id&&x.csrf&&x.exp>Date.now()?x:null}catch{return null}}
async function audit(req:Request,s:AdminSession,action:string,type:string,id=''){await dbExec('INSERT INTO audit_logs(admin_user_id,action,entity_type,entity_id,details_json,ip_address) VALUES($1,$2,$3,$4,$5,$6)',[s.user.id,action,type,id||null,'{}',String(req.headers['x-forwarded-for']||req.ip||'').split(',')[0].slice(0,45)])}

async function allPricing(){
  await ensurePricingSchema();
  const [fares,settings,distance,region,route]=await Promise.all([
    dbQuery<Row>('SELECT * FROM fare_pricing_rules ORDER BY fare_code'),
    dbQuery<Row>('SELECT * FROM pricing_settings ORDER BY setting_key'),
    dbQuery<Row>('SELECT * FROM pricing_distance_rules ORDER BY priority DESC,min_km,id'),
    dbQuery<Row>('SELECT * FROM pricing_region_rules ORDER BY priority DESC,id'),
    dbQuery<Row>('SELECT * FROM pricing_route_rules ORDER BY priority DESC,id'),
  ]);
  return {fares,settings:Object.fromEntries(settings.map(r=>[r.setting_key,r.setting_value])),distanceRules:distance,regionRules:region,routeRules:route,regions:SAUDI_REGIONS};
}

function page(){return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>التسعير والرحلات الدولية</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f6f7f9;color:#172033}.top{position:sticky;top:0;z-index:5;background:#fff;border-bottom:1px solid #e5e7eb;padding:14px 18px;display:flex;justify-content:space-between;gap:10px;align-items:center}.brand{font-size:20px;font-weight:900;color:#a77c17}.wrap{max-width:1500px;margin:auto;padding:18px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.tab,.btn{border:0;border-radius:10px;padding:10px 14px;font-weight:800;cursor:pointer}.tab{background:#fff;border:1px solid #ddd}.tab.active,.btn{background:#b58a24;color:#fff}.btn.light{background:#fff;color:#273142;border:1px solid #d7dce3}.btn.danger{background:#b42318}.grid{display:grid;grid-template-columns:minmax(340px,440px) 1fr;gap:16px}.card{background:#fff;border:1px solid #e2e6eb;border-radius:16px;padding:16px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{margin-bottom:10px}.field label{display:block;font-size:13px;font-weight:800;margin-bottom:5px}.field input,.field select,.field textarea{width:100%;padding:10px;border:1px solid #d5dae1;border-radius:9px}.field textarea{min-height:70px}.table{overflow:auto;max-height:70vh}table{width:100%;border-collapse:collapse;min-width:800px}th,td{padding:9px;border-bottom:1px solid #edf0f3;text-align:right;font-size:13px}th{background:#fafbfc;position:sticky;top:0}.hidden{display:none}.msg{min-height:24px;font-weight:700}.badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#eef2f6}.actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:900px){.grid{grid-template-columns:1fr}.row{grid-template-columns:1fr}}
</style></head><body><div class="top"><div><div class="brand">SAT Control</div><small>التسعير والرحلات الدولية</small></div><button class="btn light" onclick="top.location.hash='/admin'">العودة</button></div><div class="wrap"><div class="tabs"><button class="tab active" data-t="pricing">التسعير</button><button class="tab" data-t="international">الرحلات الدولية</button></div><div id="msg" class="msg"></div>
<section id="pricing" class="grid"><div class="card"><h3>إعدادات التسعير</h3><form id="baseForm"><div id="fareFields"></div><div class="field"><label>خصم الذهاب والعودة %</label><input id="roundDiscount" type="number" min="0" max="100" step="0.1"></div><button class="btn">حفظ الإعدادات الأساسية</button></form><hr><h3>قاعدة حسب المسافة</h3><form id="distanceForm"><input id="distanceId" type="hidden"><div class="field"><label>الاسم</label><input id="distanceName" required></div><div class="row"><div class="field"><label>من كم</label><input id="distanceMin" type="number" min="0" required></div><div class="field"><label>إلى كم - فارغ بلا حد</label><input id="distanceMax" type="number" min="0"></div></div><div class="row"><div class="field"><label>المعامل</label><input id="distanceMultiplier" type="number" step="0.01" value="1" required></div><div class="field"><label>خصم %</label><input id="distanceDiscount" type="number" min="0" max="100" step="0.1" value="0"></div></div><button class="btn">حفظ قاعدة المسافة</button></form></div><div class="card"><h3>معاينة السعر قبل الحفظ</h3><form id="previewForm"><div class="row"><div class="field"><label>المسافة كم</label><input id="previewDistance" type="number" value="950" min="1"></div><div class="field"><label>نوع الرحلة</label><select id="previewMode"><option value="oneway">ذهاب</option><option value="round">ذهاب وعودة</option></select></div></div><div class="row"><div class="field"><label>منطقة الانطلاق</label><select id="previewOriginRegion"></select></div><div class="field"><label>منطقة الوصول</label><select id="previewDestinationRegion"></select></div></div><div class="row"><div class="field"><label>مفتاح الانطلاق</label><input id="previewOriginKey" value="riyadh"></div><div class="field"><label>مفتاح الوصول</label><input id="previewDestinationKey" value="jeddah"></div></div><button class="btn">معاينة</button></form><pre id="previewResult" style="white-space:pre-wrap;background:#f8f9fb;padding:12px;border-radius:10px"></pre><h3>قواعد المسافة</h3><div class="table"><table><thead><tr><th>الاسم</th><th>النطاق</th><th>المعامل</th><th>الخصم</th><th>إجراء</th></tr></thead><tbody id="distanceRows"></tbody></table></div></div></section>
<section id="international" class="hidden"><div class="grid"><div class="card"><h3>الدول والمدن</h3><form id="countryForm"><div class="row"><div class="field"><label>رمز الدولة</label><input id="countryCode" maxlength="2" required></div><div class="field"><label>الاسم العربي</label><input id="countryAr" required></div></div><div class="field"><label>الاسم الإنجليزي</label><input id="countryEn" required></div><button class="btn">حفظ الدولة</button></form><hr><form id="cityForm"><div class="field"><label>الدولة</label><select id="intlCityCountry"></select></div><div class="field"><label>ID المدينة</label><input id="intlCityId" required></div><div class="row"><div class="field"><label>الاسم العربي</label><input id="intlCityAr" required></div><div class="field"><label>الاسم الإنجليزي</label><input id="intlCityEn" required></div></div><div class="row"><div class="field"><label>Latitude</label><input id="intlLat" type="number" step="any" required></div><div class="field"><label>Longitude</label><input id="intlLng" type="number" step="any" required></div></div><button class="btn">حفظ المدينة</button></form></div><div class="card"><h3>المسارات الدولية ونقاط التوقف</h3><form id="intlRouteForm"><input id="intlRouteId" type="hidden"><div class="field"><label>كود المسار</label><input id="intlRouteCode" required></div><div class="row"><div class="field"><label>من</label><select id="intlFrom"></select></div><div class="field"><label>إلى</label><select id="intlTo"></select></div></div><div class="row"><div class="field"><label>المسافة كم</label><input id="intlDistance" type="number" min="1" step="0.1"></div><div class="field"><label>المدة بالدقائق</label><input id="intlDuration" type="number" min="1"></div></div><div class="field"><label>نقاط التوقف - كل نقطة في سطر</label><textarea id="intlStops"></textarea></div><div class="field"><label>مسار الرحلة JSON اختياري</label><textarea id="intlPath" placeholder='[{"name":"الحدود"},{"cityId":"amman"}]'></textarea></div><div class="field"><label>ملاحظة</label><input id="intlNote"></div><button class="btn">حفظ المسار</button></form><div class="table"><table><thead><tr><th>الكود</th><th>من</th><th>إلى</th><th>المسافة</th><th>المدة</th><th>التوقفات</th><th>إجراء</th></tr></thead><tbody id="intlRouteRows"></tbody></table></div></div></div></section></div>
<script>
let csrf='',pricing={},countries=[],intlCities=[],intlRoutes=[];const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function message(t,ok=true){$('msg').textContent=t;$('msg').style.color=ok?'#176b39':'#b42318'}async function api(action,method='GET',body){const r=await fetch('/api/admin-commerce?action='+encodeURIComponent(action),{method,credentials:'include',headers:{'Content-Type':'application/json',...(method==='POST'?{'X-CSRF-Token':csrf}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'فشل الطلب');return d}
function regionOptions(){const rs=pricing.regions||[];return '<option value="">بدون تحديد</option>'+rs.map(r=>'<option value="'+r.id+'">'+esc(r.nameAr)+'</option>').join('')}function cityOptions(){return intlCities.filter(c=>c.active).map(c=>'<option value="'+esc(c.id)+'">'+esc(c.nameAr)+' - '+esc(c.countryCode)+'</option>').join('')}function render(){const fares=pricing.fares||[];$('fareFields').innerHTML=fares.map(f=>'<div class="card" style="padding:10px;margin:8px 0"><b>'+esc(f.display_name)+'</b><div class="row"><div class="field"><label>سعر/كم</label><input data-fare="'+esc(f.fare_code)+'" data-k="price_per_km" value="'+f.price_per_km+'"></div><div class="field"><label>الحد الأدنى</label><input data-fare="'+esc(f.fare_code)+'" data-k="minimum_price" value="'+f.minimum_price+'"></div></div><div class="field"><label>الحد الأقصى</label><input data-fare="'+esc(f.fare_code)+'" data-k="maximum_price" value="'+f.maximum_price+'"></div></div>').join('');$('roundDiscount').value=pricing.settings?.round_trip_discount_percent||'0';$('distanceRows').innerHTML=(pricing.distanceRules||[]).map(r=>'<tr><td>'+esc(r.name)+'</td><td>'+r.min_km+' - '+(r.max_km??'∞')+'</td><td>'+r.multiplier+'</td><td>'+r.discount_percent+'%</td><td><button class="btn danger" onclick="delDistance('+r.id+')">حذف</button></td></tr>').join('');$('previewOriginRegion').innerHTML=regionOptions();$('previewDestinationRegion').innerHTML=regionOptions();$('intlCityCountry').innerHTML=countries.map(c=>'<option value="'+c.code+'">'+esc(c.nameAr)+'</option>').join('');$('intlFrom').innerHTML=cityOptions();$('intlTo').innerHTML=cityOptions();$('intlRouteRows').innerHTML=intlRoutes.map(r=>'<tr><td>'+esc(r.routeCode)+'</td><td>'+esc(intlCities.find(c=>c.id===r.originCityId)?.nameAr||r.originCityId)+'</td><td>'+esc(intlCities.find(c=>c.id===r.destinationCityId)?.nameAr||r.destinationCityId)+'</td><td>'+r.distanceKm+' كم</td><td>'+r.durationMinutes+' د</td><td>'+esc((r.stops||[]).join(' ← '))+'</td><td><button class="btn light" onclick="editIntlRoute('+r.id+')">تعديل</button> <button class="btn danger" onclick="delIntlRoute('+r.id+')">حذف</button></td></tr>').join('')}
async function load(){try{const d=await api('summary');csrf=d.data.csrf;pricing=d.data.pricing;countries=d.data.countries;intlCities=d.data.cities;intlRoutes=d.data.routes;render();message('تم تحميل البيانات')}catch(e){message(e.message,false)}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');['pricing','international'].forEach(id=>$(id).classList.toggle('hidden',id!==b.dataset.t))});
$('baseForm').onsubmit=async e=>{e.preventDefault();try{const fares={};document.querySelectorAll('[data-fare]').forEach(i=>{fares[i.dataset.fare]??={};fares[i.dataset.fare][i.dataset.k]=Number(i.value)});await api('pricing-base-save','POST',{fares,roundTripDiscountPercent:Number($('roundDiscount').value)});await load();message('تم حفظ التسعير الأساسي')}catch(x){message(x.message,false)}};
$('distanceForm').onsubmit=async e=>{e.preventDefault();try{await api('distance-save','POST',{id:$('distanceId').value||null,name:$('distanceName').value,minKm:Number($('distanceMin').value),maxKm:$('distanceMax').value?Number($('distanceMax').value):null,multiplier:Number($('distanceMultiplier').value),discountPercent:Number($('distanceDiscount').value),active:true});await load();message('تم حفظ قاعدة المسافة')}catch(x){message(x.message,false)}};window.delDistance=async id=>{if(!confirm('حذف القاعدة؟'))return;await api('distance-delete','POST',{id});await load()};
$('previewForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('pricing-preview','POST',{distanceKm:Number($('previewDistance').value),tripMode:$('previewMode').value,originRegionId:Number($('previewOriginRegion').value)||undefined,destinationRegionId:Number($('previewDestinationRegion').value)||undefined,originKey:$('previewOriginKey').value,destinationKey:$('previewDestinationKey').value});$('previewResult').textContent=JSON.stringify(d.data,null,2)}catch(x){message(x.message,false)}};
$('countryForm').onsubmit=async e=>{e.preventDefault();try{await api('country-save','POST',{code:$('countryCode').value,nameAr:$('countryAr').value,nameEn:$('countryEn').value,active:true});await load();message('تم حفظ الدولة')}catch(x){message(x.message,false)}};
$('cityForm').onsubmit=async e=>{e.preventDefault();try{await api('international-city-save','POST',{id:$('intlCityId').value,countryCode:$('intlCityCountry').value,nameAr:$('intlCityAr').value,nameEn:$('intlCityEn').value,lat:Number($('intlLat').value),lng:Number($('intlLng').value),active:true});await load();message('تم حفظ المدينة الدولية')}catch(x){message(x.message,false)}};
$('intlRouteForm').onsubmit=async e=>{e.preventDefault();try{let path=[];if($('intlPath').value.trim())path=JSON.parse($('intlPath').value);await api('international-route-save','POST',{id:$('intlRouteId').value||null,routeCode:$('intlRouteCode').value,originCityId:$('intlFrom').value,destinationCityId:$('intlTo').value,distanceKm:Number($('intlDistance').value),durationMinutes:Number($('intlDuration').value),stops:$('intlStops').value.split('\n').map(x=>x.trim()).filter(Boolean),routePath:path,note:$('intlNote').value,active:true});await load();message('تم حفظ المسار الدولي')}catch(x){message(x.message,false)}};
window.editIntlRoute=id=>{const r=intlRoutes.find(x=>x.id===id);if(!r)return;$('intlRouteId').value=r.id;$('intlRouteCode').value=r.routeCode;$('intlFrom').value=r.originCityId;$('intlTo').value=r.destinationCityId;$('intlDistance').value=r.distanceKm;$('intlDuration').value=r.durationMinutes;$('intlStops').value=(r.stops||[]).join('\n');$('intlPath').value=JSON.stringify(r.routePath||[],null,2);$('intlNote').value=r.note||'';scrollTo({top:0,behavior:'smooth'})};window.delIntlRoute=async id=>{if(!confirm('حذف المسار الدولي؟'))return;await api('international-route-delete','POST',{id});await load()};load();
</script></body></html>`}

export async function handleAdminCommerce(req:Request,res:Response):Promise<boolean>{
  if(req.path==='/api/admin-commerce'&&req.method==='GET'&&!req.query.action){const s=session(req);if(!s){res.status(401).send('يجب تسجيل الدخول');return true}res.type('text/html').send(page());return true}
  if(!req.path.startsWith('/api/admin-commerce'))return false;
  const s=session(req);if(!s){json(res,{status:'error',message:'يجب تسجيل الدخول'},401);return true}if(req.method==='POST'&&String(req.headers['x-csrf-token']||'')!==s.csrf){json(res,{status:'error',message:'انتهت صلاحية الطلب'},419);return true}
  await ensureArchiveDatabase();await ensurePricingSchema();await ensureInternationalSchema();const action=text(req.query.action,80);
  if(action==='summary'){json(res,{status:'success',data:{csrf:s.csrf,pricing:await allPricing(),countries:await listInternationalCountries(),cities:await listInternationalCities(),routes:await listInternationalRoutes()}});return true}
  if(action==='pricing-base-save'&&req.method==='POST'){for(const[code,v]of Object.entries(req.body?.fares||{})){const x=v as any;await dbExec('UPDATE fare_pricing_rules SET price_per_km=$1,minimum_price=$2,maximum_price=$3,updated_at=CURRENT_TIMESTAMP WHERE fare_code=$4',[Math.max(0,num(x.price_per_km)),Math.max(0,num(x.minimum_price)),Math.max(num(x.minimum_price),num(x.maximum_price)),code])}await dbExec("INSERT INTO pricing_settings(setting_key,setting_value,updated_at) VALUES('round_trip_discount_percent',$1,CURRENT_TIMESTAMP) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_at=CURRENT_TIMESTAMP",[String(Math.max(0,Math.min(100,num(req.body?.roundTripDiscountPercent))))]);await audit(req,s,'update','pricing_base');json(res,{status:'success'});return true}
  if(action==='distance-save'&&req.method==='POST'){const p=req.body||{},id=Math.trunc(num(p.id));if(id)await dbExec('UPDATE pricing_distance_rules SET name=$1,min_km=$2,max_km=$3,multiplier=$4,discount_percent=$5,active=$6,updated_at=CURRENT_TIMESTAMP WHERE id=$7',[text(p.name,120),Math.max(0,num(p.minKm)),p.maxKm==null?null:Math.max(0,num(p.maxKm)),Math.max(0,num(p.multiplier,1)),Math.max(0,Math.min(100,num(p.discountPercent))),bool(p.active)?1:0,id]);else await dbExec('INSERT INTO pricing_distance_rules(name,min_km,max_km,multiplier,discount_percent,active) VALUES($1,$2,$3,$4,$5,$6)',[text(p.name,120),Math.max(0,num(p.minKm)),p.maxKm==null?null:Math.max(0,num(p.maxKm)),Math.max(0,num(p.multiplier,1)),Math.max(0,Math.min(100,num(p.discountPercent))),bool(p.active)?1:0]);json(res,{status:'success'});return true}
  if(action==='distance-delete'&&req.method==='POST'){await dbExec('DELETE FROM pricing_distance_rules WHERE id=$1',[Math.trunc(num(req.body?.id))]);json(res,{status:'success'});return true}
  if(action==='pricing-preview'&&req.method==='POST'){json(res,{status:'success',data:await calculateFarePrices({distanceKm:Math.max(1,num(req.body?.distanceKm)),originKey:text(req.body?.originKey,80)||'preview-origin',destinationKey:text(req.body?.destinationKey,80)||'preview-destination',originRegionId:Math.trunc(num(req.body?.originRegionId))||undefined,destinationRegionId:Math.trunc(num(req.body?.destinationRegionId))||undefined,tripMode:req.body?.tripMode==='round'?'round':'oneway'})});return true}
  if(action==='country-save'&&req.method==='POST'){const p=req.body||{},code=text(p.code,2).toUpperCase();if(!/^[A-Z]{2}$/.test(code)){json(res,{status:'error',message:'رمز الدولة غير صالح'},422);return true}await dbExec('INSERT INTO international_countries(country_code,name_ar,name_en,active,sort_order,updated_at) VALUES($1,$2,$3,$4,$5,CURRENT_TIMESTAMP) ON CONFLICT(country_code) DO UPDATE SET name_ar=EXCLUDED.name_ar,name_en=EXCLUDED.name_en,active=EXCLUDED.active,sort_order=EXCLUDED.sort_order,updated_at=CURRENT_TIMESTAMP',[code,text(p.nameAr,120),text(p.nameEn,120),bool(p.active)?1:0,Math.trunc(num(p.sortOrder))]);json(res,{status:'success'});return true}
  if(action==='international-city-save'&&req.method==='POST'){const p=req.body||{},id=text(p.id,60),country=text(p.countryCode,2).toUpperCase();if(!id||!/^[A-Z]{2}$/.test(country)){json(res,{status:'error',message:'بيانات المدينة غير صالحة'},422);return true}await dbExec('INSERT INTO international_cities(city_id,country_code,name_ar,name_en,latitude,longitude,active,sort_order,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,CURRENT_TIMESTAMP) ON CONFLICT(city_id) DO UPDATE SET country_code=EXCLUDED.country_code,name_ar=EXCLUDED.name_ar,name_en=EXCLUDED.name_en,latitude=EXCLUDED.latitude,longitude=EXCLUDED.longitude,active=EXCLUDED.active,sort_order=EXCLUDED.sort_order,updated_at=CURRENT_TIMESTAMP',[id,country,text(p.nameAr,160),text(p.nameEn,160),num(p.lat),num(p.lng),bool(p.active)?1:0,Math.trunc(num(p.sortOrder))]);json(res,{status:'success'});return true}
  if(action==='international-route-save'&&req.method==='POST'){const p=req.body||{},id=Math.trunc(num(p.id)),stops=Array.isArray(p.stops)?p.stops.map((x:any)=>text(x,160)).filter(Boolean):[],routePath=Array.isArray(p.routePath)?p.routePath:[];const values=[text(p.routeCode,80),text(p.originCityId,60),text(p.destinationCityId,60),Math.max(1,num(p.distanceKm)),Math.max(1,Math.trunc(num(p.durationMinutes))),JSON.stringify(stops),JSON.stringify(routePath),bool(p.active)?1:0,text(p.note,255)];if(values[1]===values[2]){json(res,{status:'error',message:'مدينة الانطلاق والوصول متطابقتان'},422);return true}if(id)await dbExec('UPDATE international_routes SET route_code=$1,origin_city_id=$2,destination_city_id=$3,distance_km=$4,duration_minutes=$5,stops_json=$6,route_path_json=$7,active=$8,note=$9,updated_at=CURRENT_TIMESTAMP WHERE id=$10',[...values,id]);else await dbExec('INSERT INTO international_routes(route_code,origin_city_id,destination_city_id,distance_km,duration_minutes,stops_json,route_path_json,active,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',values);json(res,{status:'success'});return true}
  if(action==='international-route-delete'&&req.method==='POST'){await dbExec('DELETE FROM international_routes WHERE id=$1',[Math.trunc(num(req.body?.id))]);json(res,{status:'success'});return true}
  json(res,{status:'error',message:'الإجراء غير موجود'},404);return true
}
