import type { Request, Response } from 'express';
import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import bcrypt from 'bcryptjs';
import { dbExec, dbQuery, ensureArchiveDatabase, getArchiveDocument, neonConfigured, setArchiveDocument } from './neonDb.js';

type Row = Record<string, any>;
type AdminUser = { id: number; name: string; email: string; role: string };
type AdminSession = { user: AdminUser; csrf: string; exp: number };
const COOKIE = 'sat_archive_admin';
const SECRET = process.env.SESSION_SECRET || '';
const TTL = 7 * 24 * 60 * 60 * 1000;
const json = (res: Response, body: unknown, status = 200) => res.status(status).setHeader('Cache-Control', 'no-store').json(body);
const text = (v: unknown, max = 1000) => String(v ?? '').trim().slice(0, max);
const num = (v: unknown, fallback = 0) => Number.isFinite(Number(v)) ? Number(v) : fallback;
const bool = (v: unknown) => v === true || v === 1 || v === '1' || v === 'true' || v === 'on';
const parse = <T>(v: unknown, fallback: T): T => { try { return typeof v === 'object' && v ? v as T : JSON.parse(String(v || '')) as T; } catch { return fallback; } };
const ip = (req: Request) => (String(req.headers['x-forwarded-for'] || '').split(',')[0].trim() || req.ip || req.socket.remoteAddress || '0.0.0.0').slice(0,45);
const key = () => createHash('sha256').update(SECRET || 'unconfigured').digest();
const sign = (value: string) => createHmac('sha256', key()).update(value).digest('base64url');
function cookies(header?: string) { const out: Record<string,string> = {}; for (const p of String(header||'').split(';')) { const i=p.indexOf('='); if(i>0) out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim()); } return out; }
function encodeSession(s: AdminSession) { const p=Buffer.from(JSON.stringify(s)).toString('base64url'); return `${p}.${sign(p)}`; }
function readSession(req: Request): AdminSession | null { const token=cookies(req.headers.cookie)[COOKIE]; if(!token||SECRET.length<32)return null; const [p,s]=token.split('.'); if(!p||!s)return null; const a=Buffer.from(s),b=Buffer.from(sign(p)); if(a.length!==b.length||!timingSafeEqual(a,b))return null; try{const x=JSON.parse(Buffer.from(p,'base64url').toString('utf8')) as AdminSession; return x?.user?.id&&x.csrf&&x.exp>Date.now()?x:null;}catch{return null;} }
function setSession(res: Response, s: AdminSession | null) { const secure=process.env.NODE_ENV==='production'?'; Secure':''; const value=s?encodeURIComponent(encodeSession(s)):''; res.setHeader('Set-Cookie',`${COOKIE}=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${s?Math.floor(TTL/1000):0}${secure}`); }
async function audit(req: Request,s:AdminSession|null,action:string,type:string,id='',details:unknown={}){await dbExec('INSERT INTO audit_logs(admin_user_id,action,entity_type,entity_id,details_json,ip_address) VALUES($1,$2,$3,$4,$5,$6)',[s?.user.id||null,action,type,id||null,JSON.stringify(details),ip(req)]);}
async function settings(){const rows=await dbQuery<Row>('SELECT setting_key,setting_value FROM ui_settings');return Object.fromEntries(rows.map(r=>[r.setting_key,String(r.setting_value??'')]));}
async function saveSetting(k:string,v:string,user:number){await dbExec('INSERT INTO ui_settings(setting_key,setting_value,updated_by,updated_at) VALUES($1,$2,$3,CURRENT_TIMESTAMP) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_by=EXCLUDED.updated_by,updated_at=CURRENT_TIMESTAMP',[k,v,user]);}
async function limiter(req:Request,action:string){const bucket=Math.floor(Date.now()/60000),hash=createHash('sha256').update(ip(req)).digest('hex');const rows=await dbQuery<Row>('INSERT INTO api_rate_limits(ip_hash,endpoint,window_bucket,requests,last_request_at) VALUES($1,$2,$3,1,CURRENT_TIMESTAMP) ON CONFLICT(ip_hash,endpoint,window_bucket) DO UPDATE SET requests=api_rate_limits.requests+1,last_request_at=CURRENT_TIMESTAMP RETURNING requests',[hash,`admin:${action}`,bucket]);return Number(rows[0]?.requests||0)<=(action==='login'?10:300);}
function encrypt(v:string){if(!v)return'';const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key(),iv),data=Buffer.concat([c.update(v,'utf8'),c.final()]);return`enc:v1:${iv.toString('base64url')}:${c.getAuthTag().toString('base64url')}:${data.toString('base64url')}`;}
function decrypt(v:string){if(!v.startsWith('enc:v1:'))return v;try{const[, ,i,t,d]=v.split(':'),c=createDecipheriv('aes-256-gcm',key(),Buffer.from(i,'base64url'));c.setAuthTag(Buffer.from(t,'base64url'));return Buffer.concat([c.update(Buffer.from(d,'base64url')),c.final()]).toString('utf8');}catch{return'';}}
async function telegramToken(s?:Record<string,string>){const env=text(process.env.SAT_TELEGRAM_BOT_TOKEN||process.env.TELEGRAM_BOT_TOKEN,300);if(env)return{token:env,source:'env'};const m=s||await settings(),stored=decrypt(m.telegram_bot_token||'');return{token:stored,source:stored?'stored':'none'};}
async function telegramSend(message:string){const s=await settings();if(s.telegram_enabled!=='true')return false;const{token}=await telegramToken(s),chat=text(s.telegram_chat_id,100);if(!token||!chat)return false;const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chat,text:message,parse_mode:'HTML'}),signal:AbortSignal.timeout(8000)});return r.ok;}

const datasets:Record<string,{table:string;columns:string[]}>= {
  searches:{table:'booking_searches',columns:['id','session_id','ip_address','origin_name','destination_name','travel_date','return_date','service_type','trip_type','passenger_count','created_at']},
  submissions:{table:'frontend_submissions',columns:['id','session_id','ip_address','form_name','current_step','event_name','submission_status','payload_json','created_at']},
  'assistant-messages':{table:'support_messages',columns:['id','session_id','ip_address','sender','message','current_step','created_at']},
  'security-events':{table:'security_events',columns:['id','session_id','ip_address','endpoint','rejected_fields_json','created_at']},
  'system-logs':{table:'system_logs',columns:['id','error_code','severity','component','request_path','ip_address','session_id','message','context_json','created_at']},
};
async function dataset(req:Request,res:Response,action:string){const d=datasets[action],q=req.query as Record<string,string|undefined>,where:string[]=[],params:unknown[]=[];const add=(sql:string,v:unknown)=>{params.push(v);where.push(sql.replace('?',`$${params.length}`));};if(q.ip)add('ip_address ILIKE ?',`%${q.ip.slice(0,45)}%`);if(q.session)add('session_id ILIKE ?',`%${q.session.slice(0,80)}%`);const rows=await dbQuery<Row>(`SELECT ${d.columns.join(',')} FROM ${d.table}${where.length?` WHERE ${where.join(' AND ')}`:''} ORDER BY created_at DESC LIMIT ${q.export==='csv'?5000:500}`,params);if(q.export!=='csv')return json(res,{status:'success',data:rows});const cell=(v:unknown)=>{let s=String(v??'').replace(/\0|\r/g,'').slice(0,5000);if(/^\s*[=+\-@]/.test(s))s=`'${s}`;return/[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;};const csv=['\uFEFF'+d.columns.join(','),...rows.map(r=>d.columns.map(c=>cell(r[c])).join(','))].join('\n');res.type('text/csv').setHeader('Content-Disposition',`attachment; filename="${action}-${Date.now()}.csv"`).send(csv);}

export async function handleArchiveAdmin(req:Request,res:Response):Promise<boolean>{
  if(!req.path.startsWith('/api/admin/'))return false;
  if(!neonConfigured()){json(res,{status:'error',message:'قاعدة Neon غير مربوطة. أضف DATABASE_URL ثم أعد النشر.'},503);return true;}
  await ensureArchiveDatabase();
  if(req.path==='/api/admin/install'){
    const count=Number((await dbQuery<Row>('SELECT COUNT(*)::text count FROM admin_users'))[0]?.count||0),installed=count>0;
    if(req.method==='GET'){json(res,{status:'success',data:{installed,database:'neon',sessionReady:SECRET.length>=32}});return true;}
    if(req.method==='POST'){
      if(SECRET.length<32){json(res,{status:'error',message:'SESSION_SECRET غير جاهز أو أقصر من 32 حرفًا'},503);return true;}
      if(installed){json(res,{status:'error',message:'تم إنشاء حساب المدير مسبقًا'},409);return true;}
      const name=text(req.body?.name||'مدير النظام',100),email=text(req.body?.email,190).toLowerCase(),password=String(req.body?.password||'');
      if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8){json(res,{status:'error',message:'أدخل بريدًا صحيحًا وكلمة مرور من 8 أحرف أو أكثر'},422);return true;}
      const hash=await bcrypt.hash(password,12),rows=await dbQuery<Row>('INSERT INTO admin_users(name,email,password_hash,role,active) VALUES($1,$2,$3,$4,1) RETURNING id,name,email,role',[name,email,hash,'super_admin']);await audit(req,null,'install','admin_user',String(rows[0]?.id||''),{email});json(res,{status:'success',message:'تم إنشاء حساب المدير',data:{user:rows[0]}});return true;
    }
  }
  const action=text(req.query.action||'dashboard',80);if(!(await limiter(req,action))){json(res,{status:'error',message:'طلبات كثيرة، حاول بعد دقيقة'},429);return true;}
  if(action==='login'&&req.method==='POST'){
    const email=text(req.body?.email,190).toLowerCase(),password=String(req.body?.password||''),row=(await dbQuery<Row>('SELECT id,name,email,password_hash,role,active FROM admin_users WHERE lower(email)=lower($1) AND active=1 LIMIT 1',[email]))[0],hash=String(row?.password_hash||'').replace(/^\$2y\$/,'$2b$');
    if(!row||!(await bcrypt.compare(password,hash).catch(()=>false))){json(res,{status:'error',message:'بيانات الدخول غير صحيحة'},401);return true;}
    const s:AdminSession={user:{id:Number(row.id),name:row.name,email:row.email,role:row.role},csrf:randomBytes(24).toString('hex'),exp:Date.now()+TTL};setSession(res,s);await dbExec('UPDATE admin_users SET last_login_at=CURRENT_TIMESTAMP WHERE id=$1',[row.id]);await audit(req,s,'login','session');json(res,{status:'success',data:{user:s.user,csrf:s.csrf}});return true;
  }
  const s=readSession(req);if(!s){json(res,{status:'error',message:'يجب تسجيل الدخول'},401);return true;}if(req.method==='POST'&&String(req.headers['x-csrf-token']||'')!==s.csrf){json(res,{status:'error',message:'انتهت صلاحية الطلب'},419);return true;}
  if(action==='logout'&&req.method==='POST'){await audit(req,s,'logout','session');setSession(res,null);json(res,{status:'success'});return true;}if(action==='me'){json(res,{status:'success',data:{user:s.user,csrf:s.csrf}});return true;}if(datasets[action]){await dataset(req,res,action);return true;}

  if(action==='dashboard'){const [bookings,payments,approved,pending]=await Promise.all([dbQuery<Row>('SELECT COUNT(*)::int count FROM payment_bookings'),dbQuery<Row>('SELECT COUNT(*)::int count FROM payments'),dbQuery<Row>("SELECT COUNT(*)::int count FROM payments WHERE gateway_status='approved_internal'"),dbQuery<Row>("SELECT COUNT(*)::int count FROM payments WHERE gateway_status='otp_pending'")]);const routes=(await getArchiveDocument<Row>('routes')).filter(r=>r.active===true||r.active===1).length+Number((await dbQuery<Row>('SELECT COUNT(*)::int count FROM route_overrides WHERE active=1'))[0]?.count||0);const recent=await dbQuery<Row>('SELECT payment_id,card_last4,card_brand,otp_verified,gateway_status,created_at FROM payments ORDER BY created_at DESC LIMIT 8');json(res,{status:'success',data:{stats:{bookings:Number(bookings[0]?.count||0),payments:Number(payments[0]?.count||0),approved:Number(approved[0]?.count||0),otpPending:Number(pending[0]?.count||0),routes},recentPayments:recent}});return true;}
  if(action==='routes'&&req.method==='GET'){json(res,{status:'success',data:{stations:await getArchiveDocument('stations'),overrides:await dbQuery<Row>('SELECT * FROM route_overrides ORDER BY updated_at DESC')}});return true;}
  if(action==='route-save'&&req.method==='POST'){const p=req.body||{},from=text(p.from,30),to=text(p.to,30);if(!from||!to||from===to){json(res,{status:'error',message:'المسار غير صالح'},422);return true;}await dbExec('INSERT INTO route_overrides(route_key,origin_station_id,destination_station_id,distance_km,duration_minutes,stops_json,active,service_type,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,CURRENT_TIMESTAMP) ON CONFLICT(route_key) DO UPDATE SET distance_km=EXCLUDED.distance_km,duration_minutes=EXCLUDED.duration_minutes,stops_json=EXCLUDED.stops_json,active=EXCLUDED.active,service_type=EXCLUDED.service_type,updated_at=CURRENT_TIMESTAMP',[`${from}-${to}`,from,to,Math.max(1,Math.trunc(num(p.distanceKm))),Math.max(1,Math.trunc(num(p.durationMinutes))),JSON.stringify(text(p.stops,1000).split(',').map(x=>x.trim()).filter(Boolean)),bool(p.active)?1:0,text(p.serviceType||'domestic',30)]);await audit(req,s,'save','route_override',`${from}-${to}`);json(res,{status:'success',message:'تم حفظ المسار'});return true;}
  if(action==='stations'&&req.method==='GET'){json(res,{status:'success',data:await getArchiveDocument('stations')});return true;}
  if(action==='station-save'&&req.method==='POST'){const list=await getArchiveDocument<Row>('stations'),p=req.body||{},id=text(p.id,30)||`ST-CUSTOM-${Date.now()}`,row={id,city:text(p.city,120),name:text(p.name,160),displayName:text(p.name,160),country:text(p.country||'SA',2).toUpperCase(),active:bool(p.active),latitude:num(p.latitude),longitude:num(p.longitude),mapUrl:text(p.mapUrl,500),cityId:Math.max(1,...list.map(x=>Number(x.cityId)||0))+1};const i=list.findIndex(x=>String(x.id)===id);if(i>=0)list[i]={...list[i],...row};else list.push(row);await setArchiveDocument('stations',list);await audit(req,s,'save','station',id);json(res,{status:'success',message:'تم حفظ المحطة'});return true;}
  if(action==='trips'&&req.method==='GET'){json(res,{status:'success',data:{trips:await dbQuery<Row>('SELECT * FROM managed_trips ORDER BY departure_at DESC LIMIT 200'),stations:await getArchiveDocument('stations')}});return true;}
  if(action==='trip-save'&&req.method==='POST'){const p=req.body||{},id=Math.trunc(num(p.id)),values=[text(p.tripCode,60),text(p.from,30),text(p.to,30),text(p.serviceType||'domestic',30),text(p.departureAt,40),text(p.arrivalAt,40),text(p.busLabel,100),Math.max(1,Math.trunc(num(p.seatCapacity,45))),Math.max(0,num(p.saverPrice)),Math.max(0,num(p.standardPrice)),Math.max(0,num(p.flexPrice)),Math.max(0,num(p.vipPrice)),JSON.stringify(text(p.stops,1000).split(',').map(x=>x.trim()).filter(Boolean))];if(!values[0]||!values[1]||!values[2]||!values[4]||!values[5]){json(res,{status:'error',message:'بيانات الرحلة غير مكتملة'},422);return true;}if(id)await dbExec('UPDATE managed_trips SET trip_code=$1,origin_station_id=$2,destination_station_id=$3,service_type=$4,departure_at=$5,arrival_at=$6,bus_label=$7,seat_capacity=$8,saver_price=$9,standard_price=$10,flex_price=$11,vip_price=$12,stops_json=$13,updated_at=CURRENT_TIMESTAMP WHERE id=$14',[...values,id]);else await dbExec('INSERT INTO managed_trips(trip_code,origin_station_id,destination_station_id,service_type,departure_at,arrival_at,bus_label,seat_capacity,saver_price,standard_price,flex_price,vip_price,stops_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',values);await audit(req,s,'save','managed_trip',String(id||values[0]));json(res,{status:'success',message:'تم حفظ الرحلة'});return true;}
  if(action==='trip-status'&&req.method==='POST'){const id=Math.trunc(num(req.body?.id)),status=['scheduled','delayed','cancelled'].includes(req.body?.status)?req.body.status:'scheduled',delay=Math.max(0,Math.min(1440,Math.trunc(num(req.body?.delayMinutes))));await dbExec('UPDATE managed_trips SET status=$1,delay_minutes=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$3',[status,delay,id]);await audit(req,s,'update','managed_trip',String(id),{status,delay});json(res,{status:'success'});return true;}
  if(action==='bookings'&&req.method==='GET'){json(res,{status:'success',data:await dbQuery<Row>('SELECT * FROM payment_bookings ORDER BY created_at DESC LIMIT 200')});return true;}
  if(action==='live-bookings'&&req.method==='GET'){json(res,{status:'success',data:await dbQuery<Row>("SELECT *,CASE WHEN updated_at>CURRENT_TIMESTAMP-INTERVAL '90 seconds' THEN 1 ELSE 0 END online FROM live_booking_sessions ORDER BY updated_at DESC LIMIT 200")});return true;}
  if(action==='booking-action'&&req.method==='POST'){const id=text(req.body?.bookingId,40),kind=text(req.body?.kind,30),map:Record<string,string>={confirm:'confirmed',reissue:'reissued',cancel:'cancelled'};if(!id||!map[kind]){json(res,{status:'error',message:'الإجراء غير صالح'},422);return true;}await dbExec('UPDATE payment_bookings SET status=$1,updated_at=CURRENT_TIMESTAMP WHERE booking_id=$2',[map[kind],id]);await audit(req,s,kind,'booking',id);json(res,{status:'success'});return true;}
  if(action==='booking-refund'&&req.method==='POST'){const id=text(req.body?.bookingId,40),amount=Math.max(0,num(req.body?.amount)),reason=text(req.body?.reason,255);if(!id||!amount||!reason){json(res,{status:'error',message:'بيانات الاسترداد غير مكتملة'},422);return true;}await dbExec('INSERT INTO booking_refunds(booking_id,amount,reason,created_by) VALUES($1,$2,$3,$4)',[id,amount,reason,s.user.id]);await audit(req,s,'refund','booking',id,{amount});json(res,{status:'success',message:'تم تسجيل الاسترداد'});return true;}
  if(action==='payments'&&req.method==='GET'){json(res,{status:'success',data:await dbQuery<Row>('SELECT payment_id,hold_id,card_last4,card_brand,card_entry_completed,cvv_provided,otp_verified,gateway_status,created_at,verified_at FROM payments ORDER BY created_at DESC LIMIT 100')});return true;}
  if(action==='payment-settings'&&req.method==='GET'){const m=await settings();json(res,{status:'success',data:{otp_expiry_minutes:m.otp_expiry_minutes||'5',otp_max_attempts:m.otp_max_attempts||'5'}});return true;}
  if(action==='payment-settings'&&req.method==='POST'){await saveSetting('otp_expiry_minutes',String(Math.max(1,Math.min(30,Math.trunc(num(req.body?.otpExpiryMinutes,5))))),s.user.id);await saveSetting('otp_max_attempts',String(Math.max(1,Math.min(10,Math.trunc(num(req.body?.otpMaxAttempts,5))))),s.user.id);await audit(req,s,'update','payment_settings');json(res,{status:'success',message:'تم حفظ إعدادات الدفع'});return true;}
  if(action==='settings'&&req.method==='GET'){const m=await settings();delete m.telegram_bot_token;json(res,{status:'success',data:m});return true;}
  if(action==='settings'&&req.method==='POST'){for(const[k,v]of Object.entries(req.body||{})){if(/^[a-z0-9_]{2,80}$/i.test(k)&&k!=='telegram_bot_token')await saveSetting(k,text(v,10000),s.user.id);}await audit(req,s,'update','ui_settings');json(res,{status:'success',message:'تم حفظ الإعدادات'});return true;}
  if(action==='content-versions'&&req.method==='GET'){json(res,{status:'success',data:await dbQuery<Row>('SELECT id,version_name,status,created_at,published_at FROM content_versions ORDER BY id DESC LIMIT 50')});return true;}
  if(action==='content-version-save'&&req.method==='POST'){const name=text(req.body?.name,120),content=req.body?.content;if(!name||!content||typeof content!=='object'){json(res,{status:'error',message:'اسم الإصدار والمحتوى مطلوبان'},422);return true;}const rows=await dbQuery<Row>('INSERT INTO content_versions(version_name,content_json,status,created_by) VALUES($1,$2,$3,$4) RETURNING id',[name,JSON.stringify(content),'draft',s.user.id]);json(res,{status:'success',data:{id:rows[0]?.id}});return true;}
  if(action==='content-version-publish'&&req.method==='POST'){const id=Math.trunc(num(req.body?.id)),row=(await dbQuery<Row>('SELECT content_json FROM content_versions WHERE id=$1',[id]))[0],content=parse<Record<string,unknown>>(row?.content_json,{});if(!Object.keys(content).length){json(res,{status:'error',message:'الإصدار غير موجود'},404);return true;}for(const[k,v]of Object.entries(content))await saveSetting(k,typeof v==='string'?v:JSON.stringify(v),s.user.id);await dbExec("UPDATE content_versions SET status='archived' WHERE status='published'");await dbExec("UPDATE content_versions SET status='published',published_at=CURRENT_TIMESTAMP WHERE id=$1",[id]);await audit(req,s,'publish','content_version',String(id));json(res,{status:'success'});return true;}
  if(action==='users'){json(res,{status:'success',data:await dbQuery<Row>('SELECT id,name,email,role,active,last_login_at,created_at FROM admin_users ORDER BY id')});return true;}
  if(action==='audit'){json(res,{status:'success',data:await dbQuery<Row>('SELECT a.*,u.name admin_name FROM audit_logs a LEFT JOIN admin_users u ON u.id=a.admin_user_id ORDER BY a.created_at DESC LIMIT 100')});return true;}
  if(action==='sessions'&&req.method==='GET'){json(res,{status:'success',data:await dbQuery<Row>("SELECT session_id,ip_address,current_step,blocked_until,block_reason,connected_at,last_seen_at,CASE WHEN last_seen_at>CURRENT_TIMESTAMP-INTERVAL '90 seconds' THEN 1 ELSE 0 END online FROM user_sessions ORDER BY last_seen_at DESC LIMIT 200")});return true;}
  if(action==='session-block'&&req.method==='POST'){const id=text(req.body?.sessionId,80),minutes=Math.max(1,Math.min(10080,Math.trunc(num(req.body?.minutes,60)))),reason=text(req.body?.reason||'قرار إداري',255);await dbExec("UPDATE user_sessions SET blocked_until=CURRENT_TIMESTAMP+($1::text||' minutes')::interval,block_reason=$2 WHERE session_id=$3",[minutes,reason,id]);await audit(req,s,'block','user_session',id,{minutes,reason});json(res,{status:'success'});return true;}
  if(action==='session-unblock'&&req.method==='POST'){const id=text(req.body?.sessionId,80);await dbExec('UPDATE user_sessions SET blocked_until=NULL,block_reason=NULL WHERE session_id=$1',[id]);await audit(req,s,'unblock','user_session',id);json(res,{status:'success'});return true;}
  if(action==='notifications'&&req.method==='GET'){json(res,{status:'success',data:await dbQuery<Row>('SELECT * FROM notifications ORDER BY created_at DESC LIMIT 100')});return true;}
  if(action==='notifications'&&req.method==='POST'){const p=req.body||{},title=text(p.title,160),message=text(p.message,1500),target=text(p.targetType||'all',30),actionType=text(p.actionType||'none',40);if(!title||!message||!['all','session','ip'].includes(target)||!['none','internal_step','external_url'].includes(actionType)){json(res,{status:'error',message:'بيانات الإشعار غير مكتملة'},422);return true;}const at=new Date(text(p.scheduledAt,40)||Date.now()).toISOString(),channels=(Array.isArray(p.channels)?p.channels:['socket']).filter((v:any)=>['socket','sms','email','whatsapp'].includes(v));const rows=await dbQuery<Row>('INSERT INTO notifications(title,message,target_type,target_value,action_type,action_value,channels_json,scheduled_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[title,message,target,text(p.targetValue,100)||null,actionType,text(p.actionValue,500)||null,JSON.stringify(channels.length?channels:['socket']),at,s.user.id]);json(res,{status:'success',data:{id:rows[0]?.id}});return true;}
  if(action==='telegram'&&req.method==='GET'){const m=await settings(),tok=await telegramToken(m),chat=text(m.telegram_chat_id,100),enabled=m.telegram_enabled==='true';json(res,{status:'success',data:{enabled,chatId:chat,tokenConfigured:tok.source!=='none',tokenSource:tok.source,chatConfigured:!!chat,ready:enabled&&tok.source!=='none'&&!!chat,events:parse(m.telegram_events,[])}});return true;}
  if(action==='telegram'&&req.method==='POST'){const p=req.body||{},enabled=bool(p.enabled),chat=text(p.chatId,100),token=text(p.botToken||p.bot_token,300),events=(Array.isArray(p.events)?p.events:[]).map((x:any)=>text(x,80)).filter(Boolean);if(enabled&&!chat){json(res,{status:'error',message:'أدخل Chat ID قبل تفعيل تيليجرام'},422);return true;}await saveSetting('telegram_enabled',enabled?'true':'false',s.user.id);await saveSetting('telegram_chat_id',chat,s.user.id);await saveSetting('telegram_events',JSON.stringify(events),s.user.id);if(token)await saveSetting('telegram_bot_token',encrypt(token),s.user.id);await audit(req,s,'update','telegram_settings');json(res,{status:'success'});return true;}
  if(action==='telegram-test'&&req.method==='POST'){const sent=await telegramSend('<b>✅ اختبار SAT Control</b>\nتم الاتصال من لوحة التحكم الجديدة على Neon.');json(res,{status:'success',data:{sent},message:sent?'تم إرسال رسالة الاختبار':'تحقق من Bot Token وChat ID'});return true;}
  if(action==='connectors'){json(res,{status:'success',data:await dbQuery<Row>('SELECT channel_code,enabled,provider,status,updated_at FROM channel_connectors ORDER BY channel_code')});return true;}
  if(action==='trusted-domains'){json(res,{status:'success',data:await dbQuery<Row>('SELECT id,domain,active,created_at FROM trusted_domains ORDER BY domain')});return true;}
  if(action==='distance-matrix'){const st=(await getArchiveDocument<Row>('stations')).filter(x=>(x.active===true||x.active===1)&&x.latitude&&x.longitude),sample:any[]=[];let pairs=0;for(const a of st)for(const b of st)if(a.id!==b.id){pairs++;if(sample.length<80){const p1=num(a.latitude)*Math.PI/180,p2=num(b.latitude)*Math.PI/180,dp=p2-p1,dl=(num(b.longitude)-num(a.longitude))*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2,km=Math.max(25,Math.round(6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)))*1.2));sample.push({from:a.city,to:b.city,distanceKm:km,durationMinutes:Math.ceil(((km/82)*60+25)/5)*5});}}json(res,{status:'success',data:{stationCount:st.length,pairCount:pairs,sample}});return true;}
  if(action==='pricing'&&req.method==='GET'){json(res,{status:'success',data:await dbQuery<Row>("SELECT fare_code,display_name,price_per_km,minimum_price,maximum_price,active,updated_at FROM fare_pricing_rules ORDER BY CASE fare_code WHEN 'SAVER' THEN 1 WHEN 'STANDARD' THEN 2 WHEN 'FLEX' THEN 3 WHEN 'VIP' THEN 4 ELSE 5 END")});return true;}
  if(action==='pricing'&&req.method==='POST'){for(const r of Array.isArray(req.body?.rules)?req.body.rules:[]){const code=text(r.fareCode,30).toUpperCase();if(!['SAVER','STANDARD','FLEX','VIP'].includes(code))continue;const min=Math.max(0,num(r.minimumPrice)),max=Math.max(min,num(r.maximumPrice));await dbExec('UPDATE fare_pricing_rules SET display_name=$1,price_per_km=$2,minimum_price=$3,maximum_price=$4,active=$5,updated_at=CURRENT_TIMESTAMP WHERE fare_code=$6',[text(r.displayName||code,80),Math.max(.001,Math.min(10,num(r.pricePerKm))),min,max,bool(r.active)?1:0,code]);}await audit(req,s,'update','fare_pricing_rules');json(res,{status:'success'});return true;}
  if(action==='pricing-preview'&&req.method==='GET'){const distance=Math.max(1,Math.min(10000,num(req.query.distance,100))),rows=await dbQuery<Row>('SELECT * FROM fare_pricing_rules ORDER BY fare_code');json(res,{status:'success',data:{distance,prices:rows.map(r=>({fareCode:r.fare_code,displayName:r.display_name,price:Math.round(Math.min(+r.maximum_price,Math.max(+r.minimum_price,distance*+r.price_per_km))*100)/100}))}});return true;}
  if(action==='geo-settings'&&req.method==='GET'){const m=await settings(),totals=(await dbQuery<Row>("SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE access_allowed=1)::int allowed_count,COUNT(*) FILTER(WHERE access_allowed=0)::int denied_count,COUNT(*) FILTER(WHERE last_seen_at>CURRENT_TIMESTAMP-INTERVAL '90 seconds')::int online_count FROM geo_visitors"))[0]||{},countries=await dbQuery<Row>('SELECT country_code,MAX(country_name) country_name,COUNT(*)::int visitors,COUNT(*) FILTER(WHERE access_allowed=1)::int allowed_count,COUNT(*) FILTER(WHERE access_allowed=0)::int denied_count,MAX(last_seen_at) last_seen_at FROM geo_visitors GROUP BY country_code ORDER BY visitors DESC LIMIT 30'),visitors=await dbQuery<Row>("SELECT *,CASE WHEN last_seen_at>CURRENT_TIMESTAMP-INTERVAL '90 seconds' THEN 1 ELSE 0 END online FROM geo_visitors ORDER BY last_seen_at DESC LIMIT 100");json(res,{status:'success',data:{enabled:m.geo_blocking_enabled!=='false',allowedCountries:parse(m.geo_allowed_countries,[]),title:m.geo_outside_title||'',message:m.geo_outside_message||'',ctaLabel:m.geo_outside_cta_label||'',ctaUrl:m.geo_outside_cta_url||'',unknownPolicy:m.geo_unknown_policy||'allow',cloudflareEnabled:m.geo_cloudflare_enabled==='true',cloudflareTrustedProxies:m.geo_cloudflare_trusted_proxies||'',cacheEntries:0,totals,countries,visitors}});return true;}
  if(action==='geo-settings'&&req.method==='POST'){const p=req.body||{},countries=[...new Set((Array.isArray(p.allowedCountries)?p.allowedCountries:[]).map((v:any)=>text(v,2).toUpperCase()).filter((v:string)=>/^[A-Z]{2}$/.test(v)))];if(!countries.length){json(res,{status:'error',message:'أضف دولة واحدة على الأقل'},422);return true;}const values:Record<string,string>={geo_blocking_enabled:bool(p.enabled)?'true':'false',geo_allowed_countries:JSON.stringify(countries),geo_outside_title:text(p.title,180),geo_outside_message:text(p.message,1000),geo_outside_cta_label:text(p.ctaLabel,80),geo_outside_cta_url:text(p.ctaUrl,500),geo_unknown_policy:p.unknownPolicy==='deny'?'deny':'allow',geo_cloudflare_enabled:bool(p.cloudflareEnabled)?'true':'false',geo_cloudflare_trusted_proxies:text(p.cloudflareTrustedProxies,1000)};for(const[k,v]of Object.entries(values))await saveSetting(k,v,s.user.id);await audit(req,s,'update','geo_settings');json(res,{status:'success'});return true;}
  if(action==='refunds'&&req.method==='GET'){json(res,{status:'success',data:await dbQuery<Row>('SELECT r.*,b.ticket_id,u.name admin_name FROM booking_refunds r LEFT JOIN payment_bookings b ON b.booking_id=r.booking_id LEFT JOIN admin_users u ON u.id=r.created_by ORDER BY r.created_at DESC LIMIT 200')});return true;}
  if(action==='banks'&&req.method==='GET'){json(res,{status:'success',data:await dbQuery<Row>('SELECT id,bank_key,name,name_en,color,icon_url,bins_json,enabled,sort_order,updated_at FROM payment_banks ORDER BY sort_order,name')});return true;}
  if(action==='bank-save'&&req.method==='POST'){const p=req.body||{},id=Math.trunc(num(p.id)),bankKey=text(p.bankKey,60).toLowerCase().replace(/[^a-z0-9_-]/g,''),name=text(p.name,120);if(!bankKey||!name){json(res,{status:'error',message:'اسم البنك والمفتاح مطلوبان'},422);return true;}const values=[bankKey,name,text(p.nameEn,120)||null,/^#[0-9a-f]{6}$/i.test(String(p.color||''))?p.color:'#C4A94D',text(p.iconUrl,500)||null,JSON.stringify(text(p.bins,1000).split(/[\s,]+/).map(x=>x.replace(/\D/g,'')).filter(Boolean)),bool(p.enabled)?1:0,Math.max(-999,Math.min(999,Math.trunc(num(p.sortOrder))))];if(id)await dbExec('UPDATE payment_banks SET bank_key=$1,name=$2,name_en=$3,color=$4,icon_url=$5,bins_json=$6,enabled=$7,sort_order=$8,updated_at=CURRENT_TIMESTAMP WHERE id=$9',[...values,id]);else await dbExec('INSERT INTO payment_banks(bank_key,name,name_en,color,icon_url,bins_json,enabled,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',values);json(res,{status:'success'});return true;}
  if(action==='session-command'&&req.method==='POST'){const id=text(req.body?.sessionId,80),kind=text(req.body?.kind,40),value=text(req.body?.value,500);if(!id||!['internal_step','external_url'].includes(kind)){json(res,{status:'error',message:'بيانات أمر الجلسة غير مكتملة'},422);return true;}await dbExec('INSERT INTO session_commands(session_id,command_type,command_value) VALUES($1,$2,$3)',[id,kind,value||null]);json(res,{status:'success'});return true;}
  if(action==='socket-ticket'){json(res,{status:'error',message:'التحديث اللحظي يعمل عبر polling على Vercel ولا يحتاج Socket ticket'},503);return true;}
  if(action==='health'){const start=Date.now(),checks:any[]=[];try{await dbQuery('SELECT 1 ok');checks.push({name:'Neon PostgreSQL',status:'ok',message:'متصل'});}catch{checks.push({name:'Neon PostgreSQL',status:'error',message:'غير متصل'});}checks.push({name:'Realtime',status:'warning',message:'Polling على Vercel'});json(res,{status:'success',data:{checks,totalLatencyMs:Date.now()-start,runtime:'Node/Vercel',serverTime:new Date().toISOString()}});return true;}
  if(action==='geo-cache-clear'&&req.method==='POST'){await dbExec('DELETE FROM geo_ip_cache');json(res,{status:'success'});return true;}
  json(res,{status:'error',message:'المسار غير موجود'},404);return true;
}
