import type { Request, Response } from 'express';
import { createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { dbExec, dbQuery, ensureArchiveDatabase, getArchiveDocument, neonConfigured } from './neonDb.js';

type Row = Record<string, any>;
const json=(res:Response,body:unknown,status=200)=>res.status(status).setHeader('Cache-Control','no-store').json(body);
const str=(v:unknown,max=1000)=>String(v??'').trim().slice(0,max);
const num=(v:unknown,fallback=0)=>Number.isFinite(Number(v))?Number(v):fallback;
const bool=(v:unknown)=>v===true||v===1||v==='1'||v==='true'||v==='on';
const parse=<T>(v:unknown,f:T):T=>{try{return typeof v==='object'&&v?v as T:JSON.parse(String(v||'')) as T}catch{return f}};
const ip=(req:Request)=>(str(req.headers['x-forwarded-for'],200).split(',')[0].trim()||req.ip||req.socket.remoteAddress||'0.0.0.0').slice(0,45);
const sid=(req:Request)=>{const x=str(req.headers['x-session-id'],80);return /^SES-[A-Za-z0-9-]{12,70}$/.test(x)?x:'';};
const dateOnly=(v:unknown)=>/^\d{4}-\d{2}-\d{2}$/.test(str(v,10))?str(v,10):null;
const SENSITIVE=/(card(number|_number|cvv|_cvv|expiry|_expiry)|cvv|otp|one.?time|password|passcode|pin|identity_number|document_number)/i;
function sanitize(v:unknown):unknown{if(Array.isArray(v))return v.map(sanitize);if(!v||typeof v!=='object')return typeof v==='string'?v.slice(0,5000):v;const out:Record<string,unknown>={};for(const[k,x]of Object.entries(v as Record<string,unknown>))out[k]=SENSITIVE.test(k)?'[محجوب]':sanitize(x);return out;}
function rejected(v:unknown,prefix=''):string[]{if(!v||typeof v!=='object')return[];const out:string[]=[];for(const[k,x]of Object.entries(v as Record<string,unknown>)){const p=prefix?`${prefix}.${k}`:k;if(SENSITIVE.test(k))out.push(p);else out.push(...rejected(x,p));}return out.slice(0,30);}
async function settings(){const rows=await dbQuery<Row>('SELECT setting_key,setting_value FROM ui_settings');return Object.fromEntries(rows.map(r=>[r.setting_key,String(r.setting_value??'')]));}
function secretKey(){return createHash('sha256').update(process.env.SESSION_SECRET||'unconfigured').digest();}
function decrypt(v:string){if(!v.startsWith('enc:v1:'))return v;try{const[, ,i,t,d]=v.split(':'),c=createDecipheriv('aes-256-gcm',secretKey(),Buffer.from(i,'base64url'));c.setAuthTag(Buffer.from(t,'base64url'));return Buffer.concat([c.update(Buffer.from(d,'base64url')),c.final()]).toString('utf8');}catch{return'';}}
async function telegram(event:string,data:Record<string,unknown>){const s=await settings();if(s.telegram_enabled!=='true')return;const allowed=new Set(parse<string[]>(s.telegram_events,[]));if(allowed.size&&!allowed.has(event))return;const token=str(process.env.SAT_TELEGRAM_BOT_TOKEN||process.env.TELEGRAM_BOT_TOKEN||decrypt(s.telegram_bot_token||''),300),chat=str(s.telegram_chat_id,100);if(!token||!chat)return;const clean=sanitize(data) as Record<string,unknown>,details=Object.entries(clean).filter(([,v])=>v!==''&&v!=null).slice(0,30).map(([k,v])=>`<b>${k.replace(/[<>&]/g,'')}:</b> ${String(typeof v==='object'?JSON.stringify(v):v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}`).join('\n');await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chat,text:`<b>${event}</b>${details?`\n${details}`:''}`,parse_mode:'HTML'}),signal:AbortSignal.timeout(8000)}).catch(()=>null);}
async function touch(req:Request,step='home'){const id=sid(req);if(!id)return;const address=ip(req),hash=createHash('sha256').update(address).digest('hex');await dbExec(`INSERT INTO user_sessions(session_id,ip_address,ip_hash,current_step,user_agent,last_seen_at) VALUES($1,$2,$3,$4,$5,CURRENT_TIMESTAMP) ON CONFLICT(session_id) DO UPDATE SET ip_address=EXCLUDED.ip_address,ip_hash=EXCLUDED.ip_hash,current_step=CASE WHEN $6='' THEN user_sessions.current_step ELSE $6 END,user_agent=EXCLUDED.user_agent,last_seen_at=CURRENT_TIMESTAMP`,[id,address,hash,step||'home',str(req.headers['user-agent'],255),step]);}
async function isBlocked(req:Request){const id=sid(req);if(!id)return null;const r=(await dbQuery<Row>('SELECT blocked_until,block_reason FROM user_sessions WHERE session_id=$1',[id]))[0];return r?.blocked_until&&new Date(r.blocked_until)>new Date()?r:null;}
const stations=()=>getArchiveDocument<Row>('stations');
const cities=()=>getArchiveDocument<Row>('cities');
const buses=()=>getArchiveDocument<Row>('buses');
const routes=()=>getArchiveDocument<Row>('routes');
function stationByCity(list:Row[],id:number){return list.find(s=>Number(s.cityId)===id&&(s.active===true||s.active===1));}
function haversine(a:Row,b:Row){const R=6371,p1=num(a.latitude)*Math.PI/180,p2=num(b.latitude)*Math.PI/180,dp=p2-p1,dl=(num(b.longitude)-num(a.longitude))*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
async function routeFind(from:string,to:string):Promise<Row|null>{if(!from||!to||from===to)return null;const list=await stations(),a=list.find(x=>x.id===from),b=list.find(x=>x.id===to);if(!a||!b||a.active===false||b.active===false)return null;const international=String(a.country||'SA')!==String(b.country||'SA'),documented=(await routes()).find(r=>r.from===from&&r.to===to&&(r.active===true||r.active===1)),custom=(await dbQuery<Row>('SELECT * FROM route_overrides WHERE route_key=$1 LIMIT 1',[`${from}-${to}`]))[0];if(custom&&!Number(custom.active))return null;const distance=custom?Number(custom.distance_km):documented?Math.trunc(num(documented.distance_km)):Math.max(10,Math.round(haversine(a,b)*(international?1.22:1.18))),minutes=custom?Number(custom.duration_minutes):documented?Math.trunc(num(documented.duration_minutes)):Math.ceil(((distance/82)*60+(international?90:25))/5)*5,rules=await dbQuery<Row>("SELECT * FROM fare_pricing_rules ORDER BY CASE fare_code WHEN 'SAVER' THEN 1 WHEN 'STANDARD' THEN 2 WHEN 'FLEX' THEN 3 WHEN 'VIP' THEN 4 ELSE 5 END");let fares=rules.map(r=>{const price=Math.round(Math.min(num(r.maximum_price),Math.max(num(r.minimum_price),distance*num(r.price_per_km)))*100)/100;return{code:r.fare_code,name:r.display_name,available:Number(r.active)===1,one_way_min:price,one_way_max:price,baggage:r.fare_code==='VIP'?'أمتعة واسعة وخدمة مميزة':'حقيبة يد وأمتعة شحن'};});if(international){const price=Math.round(distance*.11*100)/100;fares=[{code:'FLEX',name:'المرنة',available:true,one_way_min:price,one_way_max:price,baggage:'أمتعة شحن وتعديل مرن'}];}const available=fares.filter(f=>f.available),standard=available.find(f=>f.code==='STANDARD')||available[0],vip=available.find(f=>f.code==='VIP')||available.at(-1)||standard,usesFerry=a.country==='EG'||b.country==='EG';return{id:`AUTO-${from}-${to}`,from,to,from_city:a.city,to_city:b.city,distance_km:distance,duration_minutes:minutes,duration_text:`${Math.floor(minutes/60)} س ${minutes%60} د`,service_classes:'اقتصادية / Flex / VIP',base_price:standard?.one_way_min||0,max_price:vip?.one_way_min||0,currency:'SAR',active:true,fares,is_international:international,route_mode:usesFerry?'road_ferry':'road',route_stops:parse(custom?.stops_json,[]),ferry_fee_note:usesFerry?'رسوم العبّارة تحدد عند الحجز.':null};}
async function tripTimes(date:string,route:Row){const managed=await dbQuery<Row>("SELECT * FROM managed_trips WHERE origin_station_id=$1 AND destination_station_id=$2 AND departure_at::date=$3::date AND status<>'cancelled' ORDER BY departure_at",[route.from,route.to,date]);if(managed.length)return managed.map(t=>{const dep=new Date(t.departure_at),arr=new Date(t.arrival_at),delay=Number(t.delay_minutes||0)*60000,d1=new Date(dep.getTime()+delay),a1=new Date(arr.getTime()+delay),fares=[['SAVER','Saver',t.saver_price],['STANDARD','Standard',t.standard_price],['FLEX','Flex',t.flex_price],['VIP','VIP',t.vip_price]].map(([code,name,price])=>({code,name,available:true,one_way_min:num(price),one_way_max:num(price)})),fare=fares[0];return{id:t.trip_code,departure:d1.toISOString(),arrival:a1.toISOString(),duration_minutes:Math.max(1,Math.round((a1.getTime()-d1.getTime())/60000)),distance_km:route.distance_km,price:fare.one_way_min,available_seats:Number(t.seat_capacity),bus_class:String(t.bus_label).toUpperCase().includes('VIP')?'VIP':'STANDARD',fare_options:route.is_international?route.fares:fares,is_international:route.is_international,route_mode:route.route_mode,route_stops:route.route_stops,ferry_fee_note:route.ferry_fee_note,status:t.status};});const slots=[['05:30','direct',0],['08:00','standard',0],['11:30','transit',45],['15:00','direct',0],['19:30','standard',0]] as const,available=(route.fares||[]).filter((f:Row)=>f.available),fare=available.find((f:Row)=>f.code==='STANDARD')||available[0]||{};return slots.map(([time,kind,extra],i)=>{const dep=new Date(`${date}T${time}:00+03:00`),duration=Number(route.duration_minutes)+extra,arr=new Date(dep.getTime()+duration*60000);return{id:`${route.id}-${date}-${i+1}`,departure:dep.toISOString(),arrival:arr.toISOString(),duration_minutes:duration,distance_km:route.distance_km,trip_type:kind,price:num(fare.one_way_min||route.base_price),available_seats:Math.max(8,34-i*4),bus_class:i===3?'VIP':'STANDARD',fare_options:available,is_international:route.is_international,route_mode:route.route_mode,route_stops:route.route_stops,ferry_fee_note:route.ferry_fee_note};});}
async function geo(req:Request){const s=await settings(),country=str(req.headers['x-vercel-ip-country']||'SA',10).toUpperCase(),name=str(req.headers['x-vercel-ip-country-region']||country,100),allowedList=parse<string[]>(s.geo_allowed_countries,['SA','AE','KW','BH','QA']),allowed=s.geo_blocking_enabled==='false'||allowedList.includes(country)||(!country&&s.geo_unknown_policy!=='deny'),id=sid(req);if(id)await dbExec(`INSERT INTO geo_visitors(session_id,ip_address,country_code,country_name,access_allowed,detection_source,current_step,visit_count,last_seen_at) VALUES($1,$2,$3,$4,$5,'vercel','home',1,CURRENT_TIMESTAMP) ON CONFLICT(session_id) DO UPDATE SET ip_address=EXCLUDED.ip_address,country_code=EXCLUDED.country_code,country_name=EXCLUDED.country_name,access_allowed=EXCLUDED.access_allowed,visit_count=geo_visitors.visit_count+1,last_seen_at=CURRENT_TIMESTAMP`,[id,ip(req),country,name,allowed?1:0]);return{allowed,countryCode:country,countryName:name,title:s.geo_outside_title||'',message:s.geo_outside_message||'',ctaLabel:s.geo_outside_cta_label||'',ctaUrl:s.geo_outside_cta_url||''};}

export async function handleArchivePublic(req:Request,res:Response):Promise<boolean>{
  if(!req.path.startsWith('/api/booking'))return false;if(!neonConfigured()){json(res,{status:'error',message:'DATABASE_URL غير مربوط'},503);return true;}await ensureArchiveDatabase();let path=req.path.replace(/^\/api\/booking\/?/,'');if(!path)path='health';const blocked=await isBlocked(req);if(blocked&&/^(trips\/|booking\/|payment\/|quote$|hold-seats$|bookings$|checkout$)/.test(path)){json(res,{status:'error',message:'تم حظر هذه الجلسة مؤقتًا',reason:blocked.block_reason},403);return true;}
  if(path==='health'&&req.method==='GET'){json(res,{status:'success',data:{database:'neon',ready:true}});return true;}
  if(path==='geo/status'&&req.method==='GET'){json(res,{status:'success',data:await geo(req)});return true;}
  if(path==='session/register'&&req.method==='POST'){const step=['home','results','details','seats','payment','success','tickets','faq','more'].includes(req.body?.step)?req.body.step:'home';await touch(req,step);json(res,{status:'success',data:{sessionId:sid(req),ipReference:ip(req)}});return true;}
  if(path==='session/heartbeat'&&req.method==='POST'){await touch(req,str(req.body?.step,40));const id=sid(req),commands=id?await dbQuery<Row>('SELECT id,command_type,command_value FROM session_commands WHERE session_id=$1 AND consumed_at IS NULL ORDER BY id LIMIT 5',[id]):[];for(const c of commands)await dbExec('UPDATE session_commands SET consumed_at=CURRENT_TIMESTAMP WHERE id=$1',[c.id]);json(res,{status:'success',data:{commands:commands.map(c=>({actionType:c.command_type,actionValue:c.command_value}))}});return true;}
  if(path==='booking/live-sync'&&req.method==='POST'){const id=sid(req);if(!id){json(res,{status:'error',message:'معرف الجلسة مطلوب'},422);return true;}const p=req.body||{},step=str(p.step,40)||'home',status=str(p.status,40)||'browsing',seats=(Array.isArray(p.seats)?p.seats:[]).map((x:any)=>Math.trunc(num(x))).filter((x:number)=>x>0&&x<100).slice(0,12);await dbExec(`INSERT INTO live_booking_sessions(session_id,ip_address,origin_station_id,origin_name,destination_station_id,destination_name,travel_date,trip_id,ticket_type,fare_code,seat_numbers_json,passenger_count,current_step,status,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,CURRENT_TIMESTAMP) ON CONFLICT(session_id) DO UPDATE SET ip_address=EXCLUDED.ip_address,origin_station_id=EXCLUDED.origin_station_id,origin_name=EXCLUDED.origin_name,destination_station_id=EXCLUDED.destination_station_id,destination_name=EXCLUDED.destination_name,travel_date=EXCLUDED.travel_date,trip_id=EXCLUDED.trip_id,ticket_type=EXCLUDED.ticket_type,fare_code=EXCLUDED.fare_code,seat_numbers_json=EXCLUDED.seat_numbers_json,passenger_count=EXCLUDED.passenger_count,current_step=EXCLUDED.current_step,status=EXCLUDED.status,updated_at=CURRENT_TIMESTAMP`,[id,ip(req),str(p.originId,30)||null,str(p.originName,160)||null,str(p.destinationId,30)||null,str(p.destinationName,160)||null,dateOnly(p.travelDate),str(p.tripId,80)||null,str(p.ticketType,40)||null,str(p.fareCode,40)||null,JSON.stringify(seats),Math.max(1,Math.min(12,Math.trunc(num(p.passengerCount,1)))),step,status]);json(res,{status:'success'});return true;}
  if(path==='ui/settings'&&req.method==='GET'){const s=await settings(),keys=['maintenance_mode','home_title','support_phone','theme_primary','theme_font','announcement','logo_url','banner_url','home_sections','privacy_content','terms_content','payment_method_labels','error_messages'];json(res,{status:'success',data:Object.fromEntries(keys.map(k=>[k,s[k]||'']))});return true;}
  if(path==='events/track'&&req.method==='POST'){const event=str(req.body?.event||'unnamed_event',80),data=(req.body?.data&&typeof req.body.data==='object'?req.body.data:req.body)||{},bad=rejected(data);if(bad.length)await dbExec('INSERT INTO security_events(session_id,ip_address,endpoint,rejected_fields_json) VALUES($1,$2,$3,$4)',[sid(req)||null,ip(req),'events/track',JSON.stringify(bad)]);const safe=sanitize(data);await dbExec('INSERT INTO frontend_submissions(session_id,ip_address,form_name,current_step,event_name,payload_json,submission_status) VALUES($1,$2,$3,$4,$5,$6,$7)',[sid(req)||null,ip(req),str((data as any).formName||(data as any).formId||'interface',80),str((data as any).step,40)||null,event,JSON.stringify(safe),'accepted']);await telegram(event,safe as Record<string,unknown>);json(res,{status:'success'});return true;}
  if(path==='lookups/buses'&&req.method==='GET'){json(res,{status:'success',data:await buses()});return true;}
  if(path==='lookups/cities'&&req.method==='GET'){let items=await cities();if(bool(req.query.activeOnly))items=items.filter(x=>x.active===true||x.active===1);json(res,{status:'success',count:items.length,data:items});return true;}
  if(path==='lookups/stations'&&req.method==='GET'){const items=await stations();json(res,{status:'success',count:items.length,data:items});return true;}
  if(path==='lookups/routes'&&req.method==='GET'){const items=await routes();json(res,{status:'success',count:items.length,data:items});return true;}
  if(path==='trips/search'&&req.method==='POST'){const p=req.body||{},origin=Math.trunc(num(p.originCityId)),destination=Math.trunc(num(p.destinationCityId)),date=dateOnly(p.travelDate);if(!origin||!destination||!date||origin===destination){json(res,{status:'error',message:'بيانات المدن والتاريخ غير صالحة'},422);return true;}const list=await stations(),from=stationByCity(list,origin),to=stationByCity(list,destination);await dbExec('INSERT INTO booking_searches(session_id,ip_address,origin_city_id,destination_city_id,origin_name,destination_name,travel_date,return_date,service_type,trip_type,passenger_count,ticket_type,direct_only) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[sid(req)||null,ip(req),origin,destination,from?.city||null,to?.city||null,date,dateOnly(p.returnDate),str(p.serviceType||'domestic',30),bool(p.isRoundTrip)?'round':'oneway',Math.max(1,Math.trunc(num(p.passengerCount,1))),str(p.ticketType,40)||null,bool(p.directOnly)?1:0]);if(!from||!to){json(res,{status:'success',data:[]});return true;}const route=await routeFind(from.id,to.id);if(!route){json(res,{status:'success',data:[]});return true;}const trips=await tripTimes(date,route),data=trips.map(t=>({tripId:t.id,originCity:from.city,destinationCity:to.city,departureTime:String(t.departure).slice(11,19),arrivalTime:String(t.arrival).slice(11,19),departureDateTime:t.departure,arrivalDateTime:t.arrival,busType:t.bus_class==='VIP'?'VIP':'اقتصادية',busCapacity:t.bus_class==='VIP'?32:45,baseFare:t.price,currency:'SAR',availableSeats:t.available_seats,fareOptions:t.fare_options||[],routeId:route.id,distanceKm:t.distance_km,durationMinutes:t.duration_minutes,isInternational:t.is_international,routeMode:t.route_mode,routeStops:t.route_stops||[],ferryFeeNote:t.ferry_fee_note||''}));await telegram('search_created',{'من':from.city,'إلى':to.city,'التاريخ':date,'الركاب':Math.max(1,Math.trunc(num(p.passengerCount,1)))});json(res,{status:'success',data});return true;}
  if(path==='support/messages'&&req.method==='POST'){const message=str(req.body?.message,500).replace(/<[^>]+>/g,'');if(!message){json(res,{status:'error',message:'الرسالة مطلوبة'},422);return true;}await dbExec('INSERT INTO support_messages(session_id,ip_address,sender,message,current_step) VALUES($1,$2,$3,$4,$5)',[sid(req)||null,ip(req),['user','bot'].includes(req.body?.sender)?req.body.sender:'user',message,str(req.body?.step,40)||null]);json(res,{status:'success'},201);return true;}
  if((path==='booking/hold-seats'||path==='hold-seats')&&req.method==='POST'){const tripId=str(req.body?.tripId,80),seats=[...new Set((Array.isArray(req.body?.seatNumbers)?req.body.seatNumbers:Array.isArray(req.body?.seats)?req.body.seats:[]).map((x:any)=>Math.trunc(num(x))).filter((x:number)=>x>0&&x<100))];if(!tripId||!seats.length){json(res,{status:'error',message:'tripId وseatNumbers مطلوبان'},422);return true;}await dbExec('DELETE FROM seat_holds WHERE expires_at<=CURRENT_TIMESTAMP');const conflicts=await dbQuery<Row>('SELECT seats_json FROM seat_holds WHERE trip_id=$1 AND expires_at>CURRENT_TIMESTAMP',[tripId]);if(conflicts.some(r=>parse<number[]>(r.seats_json,[]).some(x=>seats.includes(x)))){json(res,{status:'error',message:'أحد المقاعد محجوز مؤقتًا'},409);return true;}const holdId=`HLD-${randomBytes(5).toString('hex').toUpperCase()}`,expiresAt=new Date(Date.now()+15*60000).toISOString();await dbExec('INSERT INTO seat_holds(hold_id,session_id,trip_id,seats_json,expires_at) VALUES($1,$2,$3,$4,$5)',[holdId,sid(req)||null,tripId,JSON.stringify(seats),expiresAt]);json(res,{status:'success',data:{holdId,tripId,seatNumbers:seats,createdAt:new Date().toISOString(),expiresAt}},201);return true;}
  if(path==='payment/initiate'&&req.method==='POST'){const bad=rejected(req.body);await dbExec('INSERT INTO security_events(session_id,ip_address,endpoint,rejected_fields_json) VALUES($1,$2,$3,$4)',[sid(req)||null,ip(req),'payment/initiate',JSON.stringify(bad)]);json(res,{status:'error',message:'الدفع بالبطاقة يحتاج بوابة دفع رسمية. لا يتم تخزين رقم البطاقة أو CVV أو OTP.'},422);return true;}
  if(path==='payment/verify-otp'&&req.method==='POST'){await dbExec('INSERT INTO security_events(session_id,ip_address,endpoint,rejected_fields_json) VALUES($1,$2,$3,$4)',[sid(req)||null,ip(req),'payment/verify-otp',JSON.stringify(['otp'])]);json(res,{status:'error',message:'التحقق OTP غير متاح دون مزود دفع رسمي.'},422);return true;}
  if((path==='booking/checkout'||path==='checkout'||path==='bookings')&&req.method==='POST'){const p=req.body||{},tripId=str(p.tripId,80),rawPassengers=Array.isArray(p.passengers)?p.passengers:[];if(!tripId||!rawPassengers.length){json(res,{status:'error',message:'بيانات الرحلة والمسافرين مطلوبة'},422);return true;}const passengers=rawPassengers.map((x:any)=>({type:str(x?.type,40),first_name:str(x?.first_name,100),last_name:str(x?.last_name,100),title:str(x?.title,40),nationality:str(x?.nationality,10),identity_type:str(x?.identity_type,30),identity_number:x?.identity_number?'[محجوب]':''})),bookingId=`BKG-${randomBytes(6).toString('hex').toUpperCase()}`,ticketId=`TKT-${randomBytes(6).toString('hex').toUpperCase()}`,seats=(Array.isArray(p.seatNumbers)?p.seatNumbers:Array.isArray(p.seats)?p.seats:[]).map((x:any)=>Math.trunc(num(x))).filter((x:number)=>x>0&&x<100);await dbExec('INSERT INTO payment_bookings(booking_id,payment_id,hold_id,ticket_id,status,passengers_json,phone,email,trip_id,fare_code,ticket_type,travel_date,return_date,total_amount,payment_method,seats_json) VALUES($1,NULL,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[bookingId,str(p.holdId,40)||null,ticketId,'pending_payment',JSON.stringify(passengers),str(p.phone,40)||null,str(p.email,190)||null,tripId,str(p.fareCode,40)||null,str(p.ticketType,40)||null,dateOnly(p.travelDate),dateOnly(p.returnDate),Math.max(0,num(p.totalAmount)),str(p.paymentMethod,50)||null,JSON.stringify(seats)]);const id=sid(req);if(id)await dbExec("UPDATE live_booking_sessions SET booking_id=$1,ticket_id=$2,status='completed',updated_at=CURRENT_TIMESTAMP WHERE session_id=$3",[bookingId,ticketId,id]);await telegram('booking_created',{bookingId,ticketId,tripId,phone:str(p.phone,40),totalAmount:Math.max(0,num(p.totalAmount)),passengers});json(res,{status:'success',data:{bookingId,ticketId,status:'pending_payment'}},201);return true;}
  const match=path.match(/^booking\/tickets\/([^/]+)$/);if(match&&req.method==='GET'){const row=(await dbQuery<Row>('SELECT booking_id,payment_id,hold_id,ticket_id,status,passengers_json,seats_json,created_at FROM payment_bookings WHERE ticket_id=$1 LIMIT 1',[decodeURIComponent(match[1])]))[0];if(!row){json(res,{status:'error',message:'التذكرة غير موجودة'},404);return true;}json(res,{status:'success',data:row});return true;}
  if(path==='quote'&&req.method==='POST'){const r=await routeFind(str(req.body?.from,30),str(req.body?.to,30));if(!r){json(res,{status:'error',message:'المسار غير متاح'},404);return true;}json(res,{status:'success',data:r});return true;}
  json(res,{status:'error',message:'المسار غير موجود'},404);return true;
}
