import type { Request, Response } from 'express';
import { dbExec, ensureArchiveDatabase, neonConfigured } from './neonDb.js';
import { getManagedSaudiCities } from './services/locationCatalog.js';
import { calculateSaudiRoute } from './services/routeCalculator.js';
import { calculateFarePrices, type FarePriceResult } from './services/pricingEngine.js';
import { getInternationalCity, listInternationalCities, listInternationalCountries, findInternationalRoute } from './services/internationalCatalog.js';

type PublicCity={cityId:number;cityKey:string;nameAr:string;nameEn:string;countryCode:'SA';active:boolean;region:string;regionId?:number;latitude:number;longitude:number;source:'base'|'admin'};
const json=(res:Response,body:unknown,status=200)=>res.status(status).setHeader('Cache-Control','no-store').json(body),text=(v:unknown,max=160)=>String(v??'').trim().slice(0,max),num=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f,bool=(v:unknown)=>v===true||v===1||v==='1'||v==='true'||v==='on',dateOnly=(v:unknown)=>/^\d{4}-\d{2}-\d{2}$/.test(text(v,10))?text(v,10):null;
const ip=(req:Request)=>(String(req.headers['x-forwarded-for']||'').split(',')[0].trim()||req.ip||req.socket.remoteAddress||'0.0.0.0').slice(0,45),sessionId=(req:Request)=>{const v=text(req.headers['x-session-id'],80);return /^SES-[A-Za-z0-9-]{12,70}$/.test(v)?v:''};
function syntheticCityId(key:string){let h=2166136261;for(let i=0;i<key.length;i++){h^=key.charCodeAt(i);h=Math.imul(h,16777619)}return 900000+((h>>>0)%90000000)}function numericCityId(c:{id:string;nationalAddressCityId?:number}){return c.nationalAddressCityId??syntheticCityId(c.id)}
async function publicCities():Promise<PublicCity[]>{return (await getManagedSaudiCities()).map(c=>({cityId:numericCityId(c),cityKey:c.id,nameAr:c.nameAr,nameEn:c.nameEn||c.nameAr,countryCode:'SA',active:c.active,region:c.regionAr,regionId:c.regionId,latitude:c.lat,longitude:c.lng,source:c.source}))}
async function resolveSaudiCity(value:unknown){const items=await getManagedSaudiCities(),raw=text(value,100).toLowerCase();return items.find(c=>c.active&&(c.id===raw||c.code.toLowerCase()===raw||String(numericCityId(c))===raw||c.nameAr.toLowerCase()===raw||String(c.nameEn||'').toLowerCase()===raw))}
function localTime(v:Date){return new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Riyadh',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(v)}
function fareOptions(prices:FarePriceResult[],mode:'oneway'|'round'){return prices.map(p=>({code:p.fareCode,name:p.displayName,available:true,one_way_min:p.oneWayPrice,one_way_max:p.oneWayPrice,return_one_way_price:p.returnOneWayPrice,round_trip_price:p.roundTripPrice,selected_price:p.selectedPrice,trip_mode:mode,baggage:p.fareCode==='VIP'?'أمتعة واسعة وخدمة مميزة':'حقيبة يد وأمتعة شحن',pricing_breakdown:p.breakdown}))}
function tripSlots(date:string,duration:number,routeId:string,distance:number,fares:any[],stops:string[]=[]){const slots:Array<[string,string,number]>=[['05:30','direct',0],['08:00','standard',0],['11:30','transit',45],['15:00','direct',0],['19:30','standard',0]],standard=fares.find(f=>f.code==='STANDARD')||fares[0]||{selected_price:0};return slots.map(([time,kind,extra],i)=>{const dep=new Date(`${date}T${time}:00+03:00`),dur=duration+extra,arr=new Date(dep.getTime()+dur*60000);return{id:`${routeId}-${date}-${i+1}`,departure:dep.toISOString(),arrival:arr.toISOString(),departure_time:`${time}:00`,arrival_time:localTime(arr),duration_minutes:dur,distance_km:distance,trip_type:kind,price:num(standard.selected_price),available_seats:Math.max(8,34-i*4),bus_class:i===3?'VIP':'STANDARD',fare_options:fares,stops}})}
async function recordSearch(req:Request,o:any,d:any,date:string,type:'domestic'|'international'){await dbExec('INSERT INTO booking_searches(session_id,ip_address,origin_city_id,destination_city_id,origin_name,destination_name,travel_date,return_date,service_type,trip_type,passenger_count,ticket_type,direct_only) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[sessionId(req)||null,ip(req),type==='domestic'?numericCityId(o):0,type==='domestic'?numericCityId(d):0,o.nameAr,d.nameAr,date,dateOnly(req.body?.returnDate),type,bool(req.body?.isRoundTrip)?'round':'oneway',Math.max(1,Math.min(12,Math.trunc(num(req.body?.passengerCount,1)))),text(req.body?.ticketType,40)||null,bool(req.body?.directOnly)?1:0])}

async function domesticPricing(origin:any,destination:any,route:any,mode:'oneway'|'round'){
  const back=mode==='round'?await calculateSaudiRoute(destination.id,origin.id):null;
  const prices=await calculateFarePrices({distanceKm:route.distanceKm,originKey:origin.id,destinationKey:destination.id,originRegionId:origin.regionId,destinationRegionId:destination.regionId,tripMode:mode,returnDistanceKm:back?.distanceKm,returnOriginKey:destination.id,returnDestinationKey:origin.id,returnOriginRegionId:destination.regionId,returnDestinationRegionId:origin.regionId});
  return {prices,back};
}
async function internationalPricing(origin:any,destination:any,route:any,mode:'oneway'|'round'){
  const back=mode==='round'?await findInternationalRoute(destination.id,origin.id):null;
  if(mode==='round'&&!back)throw new Error('لا يوجد مسار عودة دولي مفعّل بين المدينتين');
  const prices=await calculateFarePrices({distanceKm:route.distanceKm,originKey:`INTL:${origin.id}`,destinationKey:`INTL:${destination.id}`,tripMode:mode,returnDistanceKm:back?.distanceKm,returnOriginKey:`INTL:${destination.id}`,returnDestinationKey:`INTL:${origin.id}`});
  return {prices,back};
}

export async function handleBookingRouting(req:Request,res:Response):Promise<boolean>{
  if(!req.path.startsWith('/api/booking'))return false;const path=req.path.replace(/^\/api\/booking\/?/,'');if(!['lookups/cities','lookups/countries','lookups/international-cities','trips/search','route/preview'].includes(path))return false;if(!neonConfigured()){json(res,{status:'error',message:'DATABASE_URL غير مربوط'},503);return true}await ensureArchiveDatabase();
  if(path==='lookups/cities'&&req.method==='GET'){let items=await publicCities();if(bool(req.query.activeOnly))items=items.filter(c=>c.active);const regionId=Math.trunc(num(req.query.regionId));if(regionId)items=items.filter(c=>Number(c.regionId)===regionId);const q=text(req.query.q,100).toLowerCase();if(q)items=items.filter(c=>[c.nameAr,c.nameEn,c.cityKey,String(c.cityId)].join(' ').toLowerCase().includes(q));json(res,{status:'success',count:items.length,data:items});return true}
  if(path==='lookups/countries'&&req.method==='GET'){const data=await listInternationalCountries(bool(req.query.activeOnly));json(res,{status:'success',count:data.length,data});return true}
  if(path==='lookups/international-cities'&&req.method==='GET'){const data=await listInternationalCities(text(req.query.countryCode,2)||undefined,bool(req.query.activeOnly));json(res,{status:'success',count:data.length,data});return true}
  const type=text(req.body?.serviceType,30)==='international'||bool(req.body?.isInternational)?'international':'domestic',mode:'oneway'|'round'=bool(req.body?.isRoundTrip)||text(req.body?.tripType,20)==='round'?'round':'oneway';
  if(path==='route/preview'&&req.method==='POST'){
    try{
      if(type==='international'){const o=await getInternationalCity(text(req.body?.originCityId??req.body?.originCityKey,60)),d=await getInternationalCity(text(req.body?.destinationCityId??req.body?.destinationCityKey,60));if(!o||!d||o.id===d.id){json(res,{status:'error',message:'المدن الدولية المحددة غير صالحة'},422);return true}const r=await findInternationalRoute(o.id,d.id);if(!r){json(res,{status:'error',message:'لا يوجد مسار دولي مفعّل بين المدينتين'},404);return true}const {prices,back}=await internationalPricing(o,d,r,mode);json(res,{status:'success',data:{...r,origin:o,destination:d,returnRoute:back,fares:fareOptions(prices,mode)}});return true}
      const o=await resolveSaudiCity(req.body?.originCityId??req.body?.originCityKey??req.body?.origin),d=await resolveSaudiCity(req.body?.destinationCityId??req.body?.destinationCityKey??req.body?.destination);if(!o||!d||o.id===d.id){json(res,{status:'error',message:'المدن المحددة غير صالحة'},422);return true}const r=await calculateSaudiRoute(o.id,d.id),{prices,back}=await domesticPricing(o,d,r,mode);json(res,{status:'success',data:{...r,returnRoute:back,fares:fareOptions(prices,mode)}});return true
    }catch(e){json(res,{status:'error',message:e instanceof Error?e.message:'تعذر حساب المسار'},422);return true}
  }
  if(path==='trips/search'&&req.method==='POST'){
    const date=dateOnly(req.body?.travelDate);if(!date){json(res,{status:'error',message:'تاريخ الرحلة غير صالح'},422);return true}
    try{
      if(type==='international'){const o=await getInternationalCity(text(req.body?.originCityId??req.body?.originCityKey,60)),d=await getInternationalCity(text(req.body?.destinationCityId??req.body?.destinationCityKey,60));if(!o||!d||o.id===d.id){json(res,{status:'error',message:'بيانات المدن الدولية غير صالحة'},422);return true}const r=await findInternationalRoute(o.id,d.id);if(!r){json(res,{status:'error',message:'لا يوجد مسار دولي مفعّل بين المدينتين'},404);return true}const {prices,back}=await internationalPricing(o,d,r,mode),fares=fareOptions(prices,mode),routeId=`INTL-${r.routeCode}`,trips=tripSlots(date,r.durationMinutes,routeId,r.distanceKm,fares,r.stops);await recordSearch(req,o,d,date,'international');const data=trips.map(x=>({tripId:x.id,originCity:o.nameAr,destinationCity:d.nameAr,originCityId:o.id,destinationCityId:d.id,originCountryCode:o.countryCode,destinationCountryCode:d.countryCode,departureTime:x.departure_time,arrivalTime:x.arrival_time,departureDateTime:x.departure,arrivalDateTime:x.arrival,busType:x.bus_class==='VIP'?'VIP':'دولي',busCapacity:x.bus_class==='VIP'?32:45,baseFare:x.price,currency:'SAR',availableSeats:x.available_seats,fareOptions:x.fare_options,routeId,distanceKm:x.distance_km,durationMinutes:x.duration_minutes,routeSource:'verified',routeProvider:'admin-international-route',routeDurationText:`${Math.floor(r.durationMinutes/60)} س ${r.durationMinutes%60} د`,isInternational:true,routeMode:'road',routeStops:r.stops,routePath:r.routePath,returnRouteStops:back?.stops||[],returnRoutePath:back?.routePath||[],ferryFeeNote:''}));json(res,{status:'success',meta:{serviceType:'international',origin:o,destination:d,distanceKm:r.distanceKm,durationMinutes:r.durationMinutes,returnDistanceKm:back?.distanceKm,returnDurationMinutes:back?.durationMinutes,routeSource:'verified',routeProvider:'admin-international-route',pricingSource:'flexible-pricing-engine',tripMode:mode},data});return true}
      const o=await resolveSaudiCity(req.body?.originCityId??req.body?.originCityKey),d=await resolveSaudiCity(req.body?.destinationCityId??req.body?.destinationCityKey);if(!o||!d||o.id===d.id){json(res,{status:'error',message:'بيانات المدن والتاريخ غير صالحة'},422);return true}const r=await calculateSaudiRoute(o.id,d.id),{prices,back}=await domesticPricing(o,d,r,mode),fares=fareOptions(prices,mode),routeId=`SA-${o.id}-${d.id}`,trips=tripSlots(date,r.durationMinutes,routeId,r.distanceKm,fares);await recordSearch(req,o,d,date,'domestic');const data=trips.map(x=>({tripId:x.id,originCity:o.nameAr,destinationCity:d.nameAr,originCityId:numericCityId(o),destinationCityId:numericCityId(d),departureTime:x.departure_time,arrivalTime:x.arrival_time,departureDateTime:x.departure,arrivalDateTime:x.arrival,busType:x.bus_class==='VIP'?'VIP':'اقتصادية',busCapacity:x.bus_class==='VIP'?32:45,baseFare:x.price,currency:'SAR',availableSeats:x.available_seats,fareOptions:x.fare_options,routeId,distanceKm:x.distance_km,durationMinutes:x.duration_minutes,routeSource:r.source,routeProvider:r.provider,routeDurationText:r.durationTextAr,isInternational:false,routeMode:'road',routeStops:[],returnDistanceKm:back?.distanceKm,returnDurationMinutes:back?.durationMinutes,ferryFeeNote:''}));json(res,{status:'success',meta:{serviceType:'domestic',origin:{cityId:numericCityId(o),id:o.id,nameAr:o.nameAr,lat:o.lat,lng:o.lng},destination:{cityId:numericCityId(d),id:d.id,nameAr:d.nameAr,lat:d.lat,lng:d.lng},distanceKm:r.distanceKm,durationMinutes:r.durationMinutes,returnDistanceKm:back?.distanceKm,returnDurationMinutes:back?.durationMinutes,routeSource:r.source,routeProvider:r.provider,pricingSource:'flexible-pricing-engine',tripMode:mode},data});return true
    }catch(e){json(res,{status:'error',message:e instanceof Error?e.message:'تعذر البحث عن الرحلات'},422);return true}
  }
  return false;
}
